# Generated by Django 5.2.14 on 2026-06-08 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('community', 'Community'), ('events', 'Events'), ('general', 'General')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('subheadline', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('background_video_url', models.URLField(blank=True)),
                ('primary_cta_text', models.CharField(default='Learn More', max_length=100)),
                ('primary_cta_url', models.CharField(default='/about/', max_length=200)),
                ('secondary_cta_text', models.CharField(blank=True, default='Donate Now', max_length=100)),
                ('secondary_cta_url', models.CharField(blank=True, default='/get-involved/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default='0.55', help_text='0.0 (transparent) to 1.0 (opaque)', max_digits=3)),
            ],
            options={
                'verbose_name': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(help_text='e.g. 500, 10+, 3', max_length=50)),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, %, K', max_length=20)),
                ('icon', models.CharField(default='fa-solid fa-chart-line', help_text='Font Awesome class e.g. fa-solid fa-children', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact Statistic',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in listing pages (max 400 chars)', max_length=400)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('url', models.URLField(blank=True)),
                ('is_donor', models.BooleanField(default=False, help_text='Check if this is a donor rather than a partner')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-circle', help_text='Font Awesome class e.g. fa-solid fa-graduation-cap', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('cta_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Kids Alive Kenya', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('mission_statement', models.TextField(blank=True)),
                ('vision_statement', models.TextField(blank=True)),
                ('about_story', models.TextField(blank=True, verbose_name='Our Story')),
                ('about_story_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('value_1_title', models.CharField(blank=True, max_length=100)),
                ('value_1_text', models.TextField(blank=True)),
                ('value_1_icon', models.CharField(blank=True, default='fa-solid fa-heart', help_text='Font Awesome class e.g. fa-solid fa-heart', max_length=100)),
                ('value_2_title', models.CharField(blank=True, max_length=100)),
                ('value_2_text', models.TextField(blank=True)),
                ('value_2_icon', models.CharField(blank=True, default='fa-solid fa-hands-holding-child', help_text='Font Awesome class e.g. fa-solid fa-hands-holding-child', max_length=100)),
                ('value_3_title', models.CharField(blank=True, max_length=100)),
                ('value_3_text', models.TextField(blank=True)),
                ('value_3_icon', models.CharField(blank=True, default='fa-solid fa-seedling', help_text='Font Awesome class e.g. fa-solid fa-seedling', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed src URL')),
                ('donate_url', models.URLField(blank=True, help_text='External donation link')),
                ('volunteer_info', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('footer_tagline', models.CharField(blank=True, max_length=300)),
                ('copyright_text', models.CharField(blank=True, default='© Kids Alive Kenya. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Parent, Volunteer, Alumni', max_length=200)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
