# Generated by Django 5.2.14 on 2026-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-star', help_text='Font Awesome class e.g. fa-solid fa-star', max_length=100)),
                ('icon_color', models.CharField(blank=True, default='#f59e0b', help_text='CSS colour value e.g. #f59e0b or var(--color-primary)', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-circle', help_text='Font Awesome class e.g. fa-solid fa-cross', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Story label e.g. Linnet’s Story', max_length=200)),
                ('body', models.TextField()),
                ('person_name', models.CharField(blank=True, help_text='Name shown below the story (can be pseudonym)', max_length=200)),
                ('name_note', models.CharField(blank=True, default='Name changed to protect privacy', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impact Story',
                'verbose_name_plural': 'Impact Stories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterventionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-circle', help_text='Font Awesome class e.g. fa-solid fa-graduation-cap', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, help_text='e.g. Nyeri County or All locations', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Intervention Level',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(help_text='County name e.g. Nyeri County', max_length=100)),
                ('name', models.CharField(help_text='Centre or facility name', max_length=200)),
                ('focus', models.CharField(help_text='Program focus description', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-circle', help_text='Font Awesome class e.g. fa-solid fa-gavel', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Role',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-circle', help_text='Font Awesome class e.g. fa-solid fa-trophy', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_areas',
            field=models.CharField(blank=True, default='Nairobi\xa0| Nyeri\xa0| Kisii Counties', max_length=300, verbose_name='At a Glance — Areas of operation'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_children_reached',
            field=models.CharField(blank=True, default='Over 800 children through KAI-K programs', max_length=100, verbose_name='At a Glance — Children reached'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, verbose_name='At a Glance — Country'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_global_parent',
            field=models.CharField(blank=True, default='Kids Alive International (founded 1916, USA)', max_length=300, verbose_name='At a Glance — Global parent'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_global_presence',
            field=models.CharField(blank=True, default='Active in 8+ countries across Africa, Latin America, Asia and the Middle East', max_length=300, verbose_name='At a Glance — Global presence'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_headquarters',
            field=models.CharField(blank=True, default='Nairobi, Kenya', max_length=200, verbose_name='At a Glance — Headquarters'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_scripture',
            field=models.CharField(blank=True, default='Isaiah 1:17', max_length=100, verbose_name='At a Glance — Scripture reference'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_glance_type',
            field=models.CharField(blank=True, default='Non-profit faith-based NGO', max_length=200, verbose_name='At a Glance — Type'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_global_body_1',
            field=models.TextField(blank=True, default='Kids Alive International Kenya is part of Kids Alive International, a Christian non-profit founded in 1916 by missionaries Leslie and Ava Anglin. What began in Shantung Province, China, has grown into work spanning countries in Central America, South America, Africa, the Middle East, and Asia.', verbose_name='Global family paragraph 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_global_body_2',
            field=models.TextField(blank=True, default='Being part of this global family means access to proven models, shared research, and a network of people committed to the same mission — the flourishing of vulnerable children everywhere.', verbose_name='Global family paragraph 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_global_heading',
            field=models.CharField(blank=True, default='Part of something bigger', max_length=200, verbose_name='Global family heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_subtitle',
            field=models.TextField(blank=True, default='Kids Alive International Kenya has served vulnerable children and families across Kenya for over 20 years — rooted in faith, driven by justice.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_title',
            field=models.CharField(blank=True, default='We go where others won’t.\xa0We do what others don’t.', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_heading',
            field=models.CharField(blank=True, default='Learn to do good. Seek justice.', max_length=200, verbose_name='Mission section heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_scripture_ref',
            field=models.CharField(blank=True, default='Isaiah 1:17', max_length=100, verbose_name='Scripture reference'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_scripture_text',
            field=models.TextField(blank=True, default='Learn to do good. Seek justice. Rebuke the oppressor. Defend the fatherless. Plead for the widow.', verbose_name='Scripture quote text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_themes_heading',
            field=models.CharField(blank=True, default='Trauma into Triumph. Justice that Heals. Bonds that Mend.', max_length=300, verbose_name='Themes section heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_themes_subtitle',
            field=models.CharField(blank=True, default='Three interlocking convictions that shape everything we do for children and families.', max_length=400, verbose_name='Themes section subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_values_subtitle',
            field=models.TextField(blank=True, default='We believe we are God’s children: clean, powerful, a masterpiece, and chosen for a purpose. Every child, parent, and team member we work with is precious to Jesus — worthy of love, justice, and healing.', verbose_name='Values section subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_subtitle',
            field=models.TextField(blank=True, default='We would love to hear from you. Reach out and we will respond within 2 business days.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_title',
            field=models.CharField(blank=True, default='Contact us', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_cta_body',
            field=models.CharField(blank=True, default='Every photo tells a story made possible by supporters like you.', max_length=300, verbose_name='CTA body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_cta_heading',
            field=models.CharField(blank=True, default='Help us write more stories like these', max_length=200, verbose_name='CTA heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_subtitle',
            field=models.TextField(blank=True, default='Moments of learning, joy, and transformation from across our programs in Kenya.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_title',
            field=models.CharField(blank=True, default='Gallery', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='get_involved_hero_subtitle',
            field=models.TextField(blank=True, default='We would love to hear from you. Find us at our centres across Nairobi, Nyeri, and Kisii counties.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='get_involved_hero_title',
            field=models.CharField(blank=True, default='Get in touch', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_body',
            field=models.TextField(blank=True, default='Kids Alive Kenya is committed to rescuing, restoring, and raising children who will transform their world. We walk with children and families through the hardest realities — because every child is cherished by God.', verbose_name='About section body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_heading',
            field=models.CharField(blank=True, default='We believe every child deserves a future', max_length=300, verbose_name='About section heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_body',
            field=models.CharField(blank=True, default='Every contribution transforms a child’s life. Choose your way to help today.', max_length=400, verbose_name='CTA body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_cta_heading',
            field=models.CharField(blank=True, default='Start making a difference', max_length=200, verbose_name='CTA heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_feature_body',
            field=models.TextField(blank=True, default='We go where others won’t, and we do what others don’t — hard stories, complex trauma, legal processes, and deep systemic brokenness. Places where others often cannot go.', verbose_name='Feature box body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_feature_heading',
            field=models.CharField(blank=True, default='We do the hard things', max_length=200, verbose_name='Feature box heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_strip_body',
            field=models.TextField(blank=True, default='KAI-K runs five complementary programs across Nairobi, Nyeri, and Kisii counties — meeting children where they are and walking with them toward healing and wholeness.', verbose_name='Strip body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_strip_heading',
            field=models.CharField(blank=True, default='Restorative education, family strengthening, protective care, justice advocacy', max_length=300, verbose_name='Strip heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_strip_tagline',
            field=models.CharField(blank=True, default='Trauma into Triumph | Justice that Heals | Bonds that Mend', max_length=300, verbose_name='Strip tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_cta_body',
            field=models.CharField(blank=True, default='Your support writes the next chapter for a child in Kenya.', max_length=300, verbose_name='CTA body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_cta_heading',
            field=models.CharField(blank=True, default='Be part of this story', max_length=200, verbose_name='CTA heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_hero_subtitle',
            field=models.TextField(blank=True, default='Real numbers. Real lives. Real transformation in Kenya.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_hero_title',
            field=models.CharField(blank=True, default='Our impact', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_stories_subtitle',
            field=models.CharField(blank=True, default='These are real lives touched by KAI-K — names changed to protect privacy.', max_length=300, verbose_name='Stories section subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mdt_intro',
            field=models.TextField(blank=True, default='KAI-K employs social workers, teachers, psychologists, lawyers, and spiritual leads. These staff work together to make sure each child receives care across legal, psychological, educational, and spiritual areas.', verbose_name='Multi-disciplinary team intro'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_hero_subtitle',
            field=models.TextField(blank=True, default='Stories of hope and transformation from across Kenya.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_hero_title',
            field=models.CharField(blank=True, default='News & stories', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_sidebar_cta_body',
            field=models.TextField(blank=True, default='Your generosity directly funds programs like the ones described in this story.', verbose_name='Sidebar CTA body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_sidebar_cta_heading',
            field=models.CharField(blank=True, default='Support our work', max_length=200, verbose_name='Sidebar CTA heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='partner_body',
            field=models.TextField(blank=True, default='Is your organisation looking to partner with a credible, faith-based NGO with deep roots in the Kenyan community? We are open to institutional partnerships, church collaborations, and corporate CSR programmes.', verbose_name='Partner section body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='partner_heading',
            field=models.CharField(blank=True, default='Partner with us', max_length=200, verbose_name='Partner section heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_activities_intro',
            field=models.TextField(blank=True, default='Across all our locations, we carry out the following activities to bring healing, justice, and hope to children and families:', verbose_name='Activities intro text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_cta_body',
            field=models.CharField(blank=True, default='Your support — financial, professional, or in prayer — makes this work possible.', max_length=300, verbose_name='CTA body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_cta_heading',
            field=models.CharField(blank=True, default='Partner with us', max_length=200, verbose_name='CTA heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_hero_subtitle',
            field=models.TextField(blank=True, default='Restorative education, family strengthening, protective care, justice advocacy, and community health — working across Nairobi, Nyeri, and Kisii counties.', verbose_name='Hero subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_hero_title',
            field=models.CharField(blank=True, default='Our programs', max_length=300, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_levels_subtitle',
            field=models.TextField(blank=True, default='KAI-K operates across five complementary areas, designed to meet children where they are and walk with them toward healing and wholeness.', verbose_name='Intervention levels subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_locations_subtitle',
            field=models.TextField(blank=True, default='Our programs run in three counties, covering both rural and urban communities. Each Hope Centre connects families with social services, legal support, livelihoods training, and spiritual care.', verbose_name='Locations section subtitle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='safeguarding_text',
            field=models.TextField(blank=True, default='We are committed to safe spaces, strong boundaries, and robust protection policies for every child in our care.', verbose_name='Safeguarding statement'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schools_body',
            field=models.TextField(blank=True, default='KAI-K partners with public and private schools, county governments, and child-serving institutions to provide trauma-informed care training for staff who work with children. If your school or institution would like to equip your team with the knowledge and skills to care for children in a trauma-informed way, we would be glad to hear from you.', verbose_name='Schools section body text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schools_heading',
            field=models.CharField(blank=True, default='Schools and institutions', max_length=200, verbose_name='Schools section heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_1',
            field=models.CharField(blank=True, default='Enjoy a vibrant, life-changing relationship with God.', max_length=300, verbose_name='Vision point 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_2',
            field=models.CharField(blank=True, default='Experience emotional and physical well-being.', max_length=300, verbose_name='Vision point 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_3',
            field=models.CharField(blank=True, default='Be equipped for a life of independence and service.', max_length=300, verbose_name='Vision point 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_4',
            field=models.CharField(blank=True, default='Live life in family and community, free of fear and violence.', max_length=300, verbose_name='Vision point 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='volunteer_heading',
            field=models.CharField(blank=True, default='Volunteer', max_length=200, verbose_name='Volunteer section heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value_1_icon',
            field=models.CharField(blank=True, default='fa-solid fa-heart', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value_2_icon',
            field=models.CharField(blank=True, default='fa-solid fa-hands-holding-child', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value_3_icon',
            field=models.CharField(blank=True, default='fa-solid fa-seedling', max_length=100),
        ),
    ]
