# Generated by Django 5.2.14 on 2026-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_content_models_and_sitesettings_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('button_text', models.CharField(blank=True, default='Learn more', help_text='Text for the slide button (links to About page)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Page Slide',
                'verbose_name_plural': 'Home Page Slides',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='get_involved_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='impact_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='news_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='programs_hero_image',
            field=models.ImageField(blank=True, help_text='Leave blank to use the default static image', null=True, upload_to='hero/', verbose_name='Hero background image'),
        ),
    ]
